"""
PHANTOM AI - Professional Client Report Generator

Generates comprehensive penetration testing reports for client engagements.
Composes existing modules (HackerOneReportGenerator, ExecutiveSummaryGenerator,
ComplianceMapper, HandoffSessionGenerator) into a professional deliverable.

Output structure:
    evidence/{domain}_client/
    ├── CLIENT_REPORT.md              # Master assessment report
    ├── client_report_data.json       # Structured data
    ├── executive_summary.md          # C-level summary (standalone)
    ├── compliance_annex.md           # Compliance framework mapping
    ├── findings/
    │   ├── finding_001_{type}/
    │   │   ├── finding_report.md
    │   │   ├── finding_data.json
    │   │   └── poc.html
    │   └── ...
    ├── HANDOFF.md
    ├── handoff_data.json
    └── MANIFEST.json

Version: 1.0.0
Date: 2026-02-05
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# Severity ordering for sort
_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

# CLI compliance flag → ComplianceFramework enum value
_COMPLIANCE_FLAG_MAP = {
    "owasp": "owasp_top_10",
    "pci-dss": "pci_dss",
    "pci_dss": "pci_dss",
    "nist": "nist_800_53",
    "gdpr": "gdpr",
    "hipaa": "hipaa",
    "iso27001": "iso_27001",
    "soc2": "soc_2",
    "all": None,  # sentinel — means all frameworks
}


@dataclass
class ClientReport:
    """Complete professional client assessment report."""

    # Engagement metadata
    client_name: str
    engagement_id: str
    target: str
    date: str
    safety_mode: str
    modules_run: int
    duration_seconds: float

    # Pre-rendered markdown sections
    cover_page: str
    executive_summary: str
    scope_definition: str
    findings_summary: str
    detailed_findings: str
    compliance_annex: str
    remediation_roadmap: str

    # Per-finding artifacts
    finding_reports: List[Dict[str, Any]] = field(default_factory=list)

    # Raw data
    findings: List[Dict[str, Any]] = field(default_factory=list)

    def to_markdown(self) -> str:
        """Render full client assessment report as markdown."""
        md = []

        md.append(self.cover_page)
        md.append("")
        md.append("---")
        md.append("")

        md.append("# Table of Contents")
        md.append("")
        md.append("1. [Executive Summary](#executive-summary)")
        md.append("2. [Scope & Methodology](#scope--methodology)")
        md.append("3. [Findings Summary](#findings-summary)")
        md.append("4. [Detailed Findings](#detailed-findings)")
        md.append("5. [Remediation Roadmap](#remediation-roadmap)")
        md.append("6. [Compliance Mapping](#compliance-mapping)")
        md.append("")
        md.append("---")
        md.append("")

        md.append("## Executive Summary")
        md.append("")
        md.append(self.executive_summary)
        md.append("")

        md.append("## Scope & Methodology")
        md.append("")
        md.append(self.scope_definition)
        md.append("")

        md.append("## Findings Summary")
        md.append("")
        md.append(self.findings_summary)
        md.append("")

        md.append("## Detailed Findings")
        md.append("")
        md.append(self.detailed_findings)
        md.append("")

        md.append("## Remediation Roadmap")
        md.append("")
        md.append(self.remediation_roadmap)
        md.append("")

        md.append("## Compliance Mapping")
        md.append("")
        md.append(self.compliance_annex)
        md.append("")

        # Footer
        md.append("---")
        md.append("")
        md.append(
            f"*Report generated by PHANTOM AI on {self.date}. "
            f"Engagement: {self.engagement_id}*"
        )

        return "\n".join(md)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for JSON export."""
        return {
            "client_name": self.client_name,
            "engagement_id": self.engagement_id,
            "target": self.target,
            "date": self.date,
            "safety_mode": self.safety_mode,
            "modules_run": self.modules_run,
            "duration_seconds": self.duration_seconds,
            "findings_count": len(self.findings),
            "findings": self.findings,
            "finding_reports": [
                {k: v for k, v in fr.items() if k != "h1_report_obj"}
                for fr in self.finding_reports
            ],
        }


class ClientReportGenerator:
    """
    Generates professional penetration testing reports for client engagements.

    Composes:
    - HackerOneReportGenerator → per-finding evidence, PoC, reproduction steps
    - ExecutiveSummaryGenerator → business-level summary with financial impact
    - ComplianceMapper → framework mapping (OWASP, PCI DSS, NIST, etc.)

    Usage:
        gen = ClientReportGenerator(
            output_dir=Path("evidence/acme_client"),
            client_name="ACME Corp",
            engagement_id="ENG-2026-001",
            compliance_frameworks=["owasp", "pci-dss"],
        )
        report = gen.generate(findings=[...], scan_metadata={...})
        saved = gen.save(report)
    """

    def __init__(
        self,
        output_dir: Optional[Path] = None,
        client_name: str = "Client",
        engagement_id: str = "",
        compliance_frameworks: Optional[List[str]] = None,
    ):
        self.output_dir = Path(output_dir) if output_dir else Path("evidence")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.client_name = client_name
        self.engagement_id = engagement_id or f"PHANTOM-{datetime.now().strftime('%Y%m%d')}"
        self.compliance_frameworks = compliance_frameworks or []

        # Lazy-loaded composed generators (import at use time to avoid circular deps)
        self._h1_gen = None
        self._exec_gen = None
        self._compliance_mapper = None

    def _get_h1_gen(self):
        """Lazy-load HackerOneReportGenerator."""
        if self._h1_gen is None:
            try:
                from phantom.hackerone_report_generator import HackerOneReportGenerator
                self._h1_gen = HackerOneReportGenerator(
                    output_dir=self.output_dir / "findings",
                )
            except ImportError:
                logger.warning("HackerOneReportGenerator not available")
        return self._h1_gen

    def _get_exec_gen(self):
        """Lazy-load ExecutiveSummaryGenerator."""
        if self._exec_gen is None:
            try:
                from reporting.executive_summary import ExecutiveSummaryGenerator

                # ExecutiveSummaryGenerator requires a settings object.
                # Create a lightweight stand-in so we don't depend on
                # the full config_manager at report-generation time.
                class _MinimalSettings:
                    pass

                self._exec_gen = ExecutiveSummaryGenerator(
                    settings=_MinimalSettings(),
                    compliance_mapper=self._get_compliance_mapper(),
                )
            except (ImportError, Exception) as e:
                logger.warning(f"ExecutiveSummaryGenerator not available: {e}")
        return self._exec_gen

    def _get_compliance_mapper(self):
        """Lazy-load ComplianceMapper with selected frameworks."""
        if self._compliance_mapper is None:
            try:
                from phantom.compliance_mapper import ComplianceMapper, ComplianceFramework

                # Map CLI flags to enum values
                if "all" in self.compliance_frameworks:
                    frameworks = list(ComplianceFramework)
                else:
                    frameworks = []
                    for flag in self.compliance_frameworks:
                        enum_val = _COMPLIANCE_FLAG_MAP.get(flag)
                        if enum_val:
                            try:
                                frameworks.append(ComplianceFramework(enum_val))
                            except ValueError:
                                pass
                    if not frameworks:
                        frameworks = list(ComplianceFramework)

                self._compliance_mapper = ComplianceMapper(frameworks=frameworks)
            except ImportError:
                logger.warning("ComplianceMapper not available")
        return self._compliance_mapper

    def generate(
        self,
        findings: List[Dict[str, Any]],
        scan_metadata: Optional[Dict[str, Any]] = None,
    ) -> ClientReport:
        """Generate a complete client assessment report."""
        meta = scan_metadata or {}
        date_str = meta.get("date", datetime.now().strftime("%Y-%m-%d %H:%M"))
        target = meta.get("target", "")

        # Sort by severity
        sorted_findings = sorted(
            findings,
            key=lambda f: _SEVERITY_ORDER.get(
                self._get_severity(f).lower(), 5
            ),
        )

        # 1. Generate per-finding reports (evidence, PoC, steps)
        finding_reports = self._generate_per_finding_reports(sorted_findings)

        # 2. Executive summary
        executive_summary = self._generate_executive_summary(
            sorted_findings, target, meta
        )

        # 3. Compliance annex
        compliance_annex = self._generate_compliance_annex(
            sorted_findings, target, meta
        )

        return ClientReport(
            client_name=self.client_name,
            engagement_id=self.engagement_id,
            target=target,
            date=date_str,
            safety_mode=meta.get("safety_mode", "standard"),
            modules_run=meta.get("modules_run", 0),
            duration_seconds=meta.get("duration_seconds", 0),
            cover_page=self._build_cover_page(target, date_str, meta),
            executive_summary=executive_summary,
            scope_definition=self._build_scope_definition(target, meta),
            findings_summary=self._build_findings_summary(sorted_findings),
            detailed_findings=self._build_detailed_findings(
                sorted_findings, finding_reports
            ),
            compliance_annex=compliance_annex,
            remediation_roadmap=self._build_remediation_roadmap(sorted_findings),
            finding_reports=finding_reports,
            findings=sorted_findings,
        )

    def save(
        self,
        report: ClientReport,
        formats: Optional[List[str]] = None,
    ) -> Dict[str, str]:
        """Save client report and all artifacts to disk."""
        if formats is None:
            formats = ["md", "json"]

        self.output_dir.mkdir(parents=True, exist_ok=True)
        saved = {}

        # Master report
        if "md" in formats:
            md_path = self.output_dir / "CLIENT_REPORT.md"
            md_path.write_text(report.to_markdown())
            saved["md"] = str(md_path)

        if "json" in formats:
            json_path = self.output_dir / "client_report_data.json"
            json_path.write_text(json.dumps(report.to_dict(), indent=2, default=str))
            saved["json"] = str(json_path)

        # Standalone executive summary
        if report.executive_summary:
            exec_path = self.output_dir / "executive_summary.md"
            exec_path.write_text(
                f"# Executive Summary — {report.client_name}\n\n"
                f"**Engagement:** {report.engagement_id}\n"
                f"**Target:** {report.target}\n"
                f"**Date:** {report.date}\n\n---\n\n"
                + report.executive_summary
            )
            saved["executive_summary"] = str(exec_path)

        # Standalone compliance annex
        if report.compliance_annex and report.compliance_annex != "*No compliance mapping requested.*":
            comp_path = self.output_dir / "compliance_annex.md"
            comp_path.write_text(
                f"# Compliance Mapping — {report.client_name}\n\n"
                f"**Engagement:** {report.engagement_id}\n"
                f"**Target:** {report.target}\n\n---\n\n"
                + report.compliance_annex
            )
            saved["compliance_annex"] = str(comp_path)

        # Per-finding reports + PoC files
        for fr in report.finding_reports:
            for fmt_key, fpath in fr.get("files", {}).items():
                # Files already saved by _generate_per_finding_reports
                pass

        logger.info(f"Client report saved to {self.output_dir}")
        return saved

    # ------------------------------------------------------------------
    # Per-finding report generation
    # ------------------------------------------------------------------

    def _generate_per_finding_reports(
        self, findings: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Generate individual reports for each finding using HackerOneReportGenerator."""
        h1_gen = self._get_h1_gen()
        if not h1_gen:
            return []

        reports = []
        for i, finding in enumerate(findings, 1):
            try:
                # Unwrap ValidatedFinding if needed
                raw = finding
                if isinstance(finding, dict) and "finding" in finding and isinstance(finding["finding"], dict):
                    raw = finding["finding"]

                # Generate H1 report (handles evidence, PoC, steps, classification)
                h1_report = h1_gen.generate_report(raw)

                # Save per-finding artifacts
                saved_files = h1_gen.save_report(h1_report, formats=["md", "json", "html"])

                reports.append({
                    "index": i,
                    "title": h1_report.title,
                    "severity": h1_report.severity,
                    "cwe": h1_report.cwe,
                    "cvss_score": h1_report.cvss_score,
                    "files": saved_files,
                    "exploit_evidence": h1_report.exploit_evidence,
                    "steps": [
                        {
                            "description": s.description,
                            "command": s.curl_command or "",
                            "expected": s.expected_result or "",
                            "actual": s.actual_result or "",
                        }
                        for s in h1_report.steps_to_reproduce
                    ],
                    "remediation": h1_report.remediation,
                    "summary": h1_report.summary,
                })

            except Exception as e:
                logger.debug(f"Failed to generate finding report {i}: {e}")
                reports.append({
                    "index": i,
                    "title": raw.get("name", raw.get("title", "Unknown")),
                    "severity": self._get_severity(finding),
                    "cwe": raw.get("cwe", ""),
                    "cvss_score": raw.get("cvss_score", 0),
                    "files": {},
                    "exploit_evidence": [],
                    "steps": [],
                    "remediation": raw.get("remediation", ""),
                    "summary": raw.get("description", ""),
                })

        return reports

    # ------------------------------------------------------------------
    # Executive Summary
    # ------------------------------------------------------------------

    def _generate_executive_summary(
        self,
        findings: List[Dict[str, Any]],
        target: str,
        meta: Dict[str, Any],
    ) -> str:
        """Generate executive summary using ExecutiveSummaryGenerator."""
        exec_gen = self._get_exec_gen()
        if exec_gen:
            try:
                # Flatten findings for exec generator (expects severity, type, etc. at top level)
                flat_findings = []
                for f in findings:
                    raw = f
                    if isinstance(f, dict) and "finding" in f and isinstance(f["finding"], dict):
                        raw = f["finding"]
                    flat_findings.append({
                        "severity": self._get_severity(f).upper(),
                        "type": raw.get("type", raw.get("vulnerability_type", "unknown")),
                        "name": raw.get("name", raw.get("title", "Unknown")),
                        "host": raw.get("host", raw.get("url", "")),
                        "description": raw.get("description", ""),
                        "cvss_score": raw.get("cvss_score", 0),
                    })

                summary = exec_gen.generate_summary(
                    findings=flat_findings,
                    target=target,
                    scan_metadata=meta,
                )
                return exec_gen.render_report(summary, format="markdown")
            except Exception as e:
                logger.debug(f"ExecutiveSummaryGenerator failed: {e}")

        # Fallback: simple executive summary
        return self._build_fallback_executive_summary(findings, target)

    def _build_fallback_executive_summary(
        self, findings: List[Dict[str, Any]], target: str
    ) -> str:
        """Fallback executive summary if ExecutiveSummaryGenerator is unavailable."""
        sev_counts: Dict[str, int] = {}
        for f in findings:
            sev = self._get_severity(f).upper()
            sev_counts[sev] = sev_counts.get(sev, 0) + 1

        total = len(findings)
        critical = sev_counts.get("CRITICAL", 0)
        high = sev_counts.get("HIGH", 0)

        if critical > 0:
            risk = "CRITICAL"
            urgency = "Immediate remediation required."
        elif high > 0:
            risk = "HIGH"
            urgency = "Prompt remediation recommended."
        elif total > 0:
            risk = "MODERATE"
            urgency = "Planned remediation recommended."
        else:
            risk = "LOW"
            urgency = "No significant vulnerabilities identified."

        parts = [
            f"A security assessment of **{target}** identified "
            f"**{total} finding(s)** across the following severity levels:",
            "",
        ]
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            count = sev_counts.get(sev, 0)
            if count > 0:
                parts.append(f"- **{sev}:** {count}")
        parts.append("")
        parts.append(f"**Overall Risk Rating:** {risk}")
        parts.append(f"**Recommendation:** {urgency}")

        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Compliance Annex
    # ------------------------------------------------------------------

    def _generate_compliance_annex(
        self,
        findings: List[Dict[str, Any]],
        target: str,
        meta: Dict[str, Any],
    ) -> str:
        """Generate compliance framework mapping."""
        if not self.compliance_frameworks:
            return "*No compliance mapping requested.*"

        mapper = self._get_compliance_mapper()
        if not mapper:
            return "*Compliance mapper not available.*"

        try:
            # Flatten findings for compliance mapper
            flat_findings = []
            for f in findings:
                raw = f
                if isinstance(f, dict) and "finding" in f and isinstance(f["finding"], dict):
                    raw = f["finding"]
                flat_findings.append({
                    "id": raw.get("id", raw.get("name", "")),
                    "type": raw.get("type", raw.get("vulnerability_type", "unknown")),
                    "severity": self._get_severity(f),
                    "name": raw.get("name", ""),
                })

            # Map findings to frameworks
            mappings = mapper.map_findings(flat_findings)

            # Generate compliance report
            scan_id = meta.get("scan_id", self.engagement_id)
            comp_report = mapper.generate_report(scan_id=scan_id, target=target)

            return self._render_compliance_markdown(mappings, comp_report, flat_findings)
        except Exception as e:
            logger.debug(f"Compliance mapping failed: {e}")
            return f"*Compliance mapping error: {e}*"

    def _render_compliance_markdown(
        self,
        mappings: list,
        comp_report: Any,
        findings: List[Dict[str, Any]],
    ) -> str:
        """Render compliance mappings as markdown."""
        lines = []

        # Framework coverage summary
        lines.append("### Frameworks Covered")
        lines.append("")
        if hasattr(comp_report, "frameworks_covered"):
            for fw in comp_report.frameworks_covered:
                lines.append(f"- {fw}")
        lines.append("")

        # OWASP Top 10 coverage
        if hasattr(comp_report, "owasp_coverage") and comp_report.owasp_coverage:
            lines.append("### OWASP Top 10 2021 Coverage")
            lines.append("")
            lines.append("| Category | Findings |")
            lines.append("|----------|----------|")
            for cat, count in sorted(comp_report.owasp_coverage.items()):
                lines.append(f"| {cat} | {count} |")
            lines.append("")

        # PCI DSS coverage
        if hasattr(comp_report, "pci_dss_coverage") and comp_report.pci_dss_coverage:
            lines.append("### PCI DSS 4.0 Requirements")
            lines.append("")
            lines.append("| Requirement | Findings |")
            lines.append("|-------------|----------|")
            for req, count in sorted(comp_report.pci_dss_coverage.items()):
                lines.append(f"| Req {req} | {count} |")
            lines.append("")

        # Per-finding mapping table
        lines.append("### Per-Finding Compliance Mapping")
        lines.append("")
        lines.append("| Finding | CWE | OWASP | PCI DSS | NIST |")
        lines.append("|---------|-----|-------|---------|------|")
        for i, mapping in enumerate(mappings):
            finding_name = findings[i]["name"] if i < len(findings) else "—"
            m = mapping if isinstance(mapping, dict) else (mapping.to_dict() if hasattr(mapping, "to_dict") else {})
            maps = m.get("mappings", {}) if isinstance(m, dict) else {}

            # Handle ComplianceMapping objects directly
            if hasattr(mapping, "cwe_ids"):
                cwe = ", ".join(f"CWE-{c}" for c in mapping.cwe_ids[:2]) or "—"
                owasp = ", ".join(mapping.owasp_categories[:2]) or "—"
                pci = ", ".join(mapping.pci_dss_requirements[:2]) or "—"
                nist = ", ".join(mapping.nist_controls[:2]) or "—"
            else:
                cwe = ", ".join(maps.get("cwe", [])[:2]) or "—"
                owasp = ", ".join(maps.get("owasp_top_10", [])[:2]) or "—"
                pci = ", ".join(maps.get("pci_dss", [])[:2]) or "—"
                nist = ", ".join(maps.get("nist_800_53", [])[:2]) or "—"

            lines.append(f"| {finding_name} | {cwe} | {owasp} | {pci} | {nist} |")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _build_cover_page(
        self, target: str, date_str: str, meta: Dict[str, Any]
    ) -> str:
        """Build professional cover page."""
        duration_min = meta.get("duration_seconds", 0) / 60
        return "\n".join([
            f"# Penetration Test Report",
            "",
            f"## {self.client_name}",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Client** | {self.client_name} |",
            f"| **Engagement ID** | `{self.engagement_id}` |",
            f"| **Target** | `{target}` |",
            f"| **Date** | {date_str} |",
            f"| **Assessment Type** | Automated Penetration Test |",
            f"| **Safety Mode** | `{meta.get('safety_mode', 'standard')}` |",
            f"| **Modules Executed** | {meta.get('modules_run', 0)} |",
            f"| **Duration** | {duration_min:.1f} min |",
            f"| **Tool** | PHANTOM AI |",
            "",
            "**CONFIDENTIAL** — This document contains sensitive security findings. "
            "Distribution is restricted to authorized personnel only.",
        ])

    def _build_scope_definition(
        self, target: str, meta: Dict[str, Any]
    ) -> str:
        """Build scope and methodology section."""
        lines = [
            "### Target Scope",
            "",
            f"- **Primary Target:** `{target}`",
            f"- **Safety Mode:** `{meta.get('safety_mode', 'standard')}`",
            f"- **Modules Executed:** {meta.get('modules_run', 0)}",
            "",
            "### Methodology",
            "",
            "The assessment followed an automated penetration testing methodology:",
            "",
            "1. **Reconnaissance** — Subdomain enumeration, technology fingerprinting, endpoint discovery",
            "2. **Vulnerability Scanning** — Automated testing across 47+ security modules",
            "3. **Exploitation Verification** — Evidence-based validation with real HTTP captures",
            "4. **Evidence Collection** — Full request/response pairs, PoC generation",
            "5. **Report Generation** — Automated classification, compliance mapping, remediation guidance",
            "",
            "### Limitations",
            "",
            "- Testing was conducted in `{mode}` safety mode".format(mode=meta.get("safety_mode", "standard")),
            "- Results reflect the state of the application at time of testing",
            "- Some vulnerability classes require manual verification for full confirmation",
        ]
        return "\n".join(lines)

    def _build_findings_summary(
        self, findings: List[Dict[str, Any]]
    ) -> str:
        """Build findings overview table."""
        lines = [
            "| # | Finding | Severity | CVSS | CWE | Host |",
            "|---|---------|----------|------|-----|------|",
        ]
        for i, f in enumerate(findings, 1):
            raw = f["finding"] if isinstance(f, dict) and "finding" in f else f
            title = raw.get("name", raw.get("title", raw.get("type", "Unknown")))
            sev = self._get_severity(f).upper()
            cvss = float(raw.get("cvss_score", 0) or 0)
            cwe = raw.get("cwe", "")
            host = raw.get("host", raw.get("url", ""))
            lines.append(
                f"| {i} | {title} | **{sev}** | {cvss} | {cwe} | `{host}` |"
            )

        # Severity breakdown
        sev_counts: Dict[str, int] = {}
        for f in findings:
            sev = self._get_severity(f).upper()
            sev_counts[sev] = sev_counts.get(sev, 0) + 1

        lines.append("")
        lines.append("**Severity Breakdown:**")
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            count = sev_counts.get(sev, 0)
            if count > 0:
                bar = "█" * count
                lines.append(f"- {sev}: {bar} ({count})")

        return "\n".join(lines)

    def _build_detailed_findings(
        self,
        findings: List[Dict[str, Any]],
        finding_reports: List[Dict[str, Any]],
    ) -> str:
        """Build detailed findings section with evidence from per-finding reports."""
        sections = []

        for i, f in enumerate(findings):
            raw = f["finding"] if isinstance(f, dict) and "finding" in f else f
            title = raw.get("name", raw.get("title", raw.get("type", "Unknown")))
            sev = self._get_severity(f).upper()
            cvss = float(raw.get("cvss_score", 0) or 0)
            cwe = raw.get("cwe", "")
            host = raw.get("host", raw.get("url", ""))
            desc = raw.get("description", "")

            section = [f"### {i+1}. {title}"]
            section.append("")
            section.append(f"**Severity:** {sev} | **CVSS:** {cvss} | **CWE:** {cwe}")
            section.append(f"**Host:** `{host}`")
            section.append("")

            if desc:
                section.append(desc[:600])
                section.append("")

            # Evidence from per-finding report
            fr = finding_reports[i] if i < len(finding_reports) else {}

            if fr.get("exploit_evidence"):
                section.append("#### Exploit Evidence")
                section.append("")
                for ev in fr["exploit_evidence"]:
                    label = ev.get("label", "Test")
                    section.append(f"**{label}**")
                    section.append("")
                    if ev.get("request"):
                        section.append("**Request:**")
                        section.append("```http")
                        section.append(ev["request"][:500])
                        section.append("```")
                    if ev.get("response"):
                        section.append("**Response:**")
                        section.append("```http")
                        section.append(ev["response"][:500])
                        section.append("```")
                    section.append("")

            # Reproduction steps
            if fr.get("steps"):
                section.append("#### Reproduction Steps")
                section.append("")
                for j, step in enumerate(fr["steps"], 1):
                    section.append(f"**Step {j}:** {step.get('description', '')}")
                    if step.get("command"):
                        section.append(f"```bash\n{step['command']}\n```")
                    section.append("")

            # Remediation
            remediation = fr.get("remediation") or raw.get("remediation", "")
            if remediation:
                section.append(f"#### Remediation")
                section.append("")
                section.append(remediation[:400])
                section.append("")

            # Link to per-finding artifacts
            files = fr.get("files", {})
            if files:
                section.append("#### Artifacts")
                section.append("")
                for fmt, fpath in files.items():
                    section.append(f"- `{fmt}`: `{fpath}`")
                section.append("")

            sections.append("\n".join(section))

        return "\n---\n\n".join(sections)

    def _build_remediation_roadmap(
        self, findings: List[Dict[str, Any]]
    ) -> str:
        """Build prioritized remediation roadmap."""
        effort_map = {
            "CRITICAL": ("Immediate", "Data breach / full compromise"),
            "HIGH": ("1-2 weeks", "Sensitive data exposure"),
            "MEDIUM": ("2-4 weeks", "Limited data exposure"),
            "LOW": ("Next sprint", "Minor information leak"),
            "INFO": ("Backlog", "Best practice improvement"),
        }

        lines = [
            "| Priority | Finding | Timeline | Business Impact |",
            "|----------|---------|----------|-----------------|",
        ]

        for i, f in enumerate(findings, 1):
            raw = f["finding"] if isinstance(f, dict) and "finding" in f else f
            title = raw.get("name", raw.get("title", raw.get("type", "Unknown")))
            sev = self._get_severity(f).upper()
            timeline, impact = effort_map.get(sev, ("—", "—"))
            lines.append(f"| P{i} | {title} | {timeline} | {impact} |")

        lines.append("")
        lines.append("**Priority Legend:** P1 = Highest priority (fix first)")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_severity(self, finding: Dict[str, Any]) -> str:
        """Extract severity from a finding dict (handles nested structures)."""
        if isinstance(finding, dict) and "finding" in finding:
            finding = finding["finding"]
        return (
            finding.get("severity", "")
            or finding.get("risk", "")
            or "info"
        )
