"""
Utility modules.
"""

from .logger import get_logger, setup_logging
from .rate_limiter import RateLimiter
from .validators import validate_target, validate_url, validate_ip
from .network_utils import async_request, resolve_domain
from .cvss_calculator import CVSSCalculator
from .http_transport import (
    HTTP_TRANSPORT_VERSION,
    HTTPTransportEngine,
    URLCanonicalizer,
    TransportResult,
    CanonicalURL,
    ResponseLayer,
    RequestStatus,
    ProtocolPolicy,
    SmartBackoff,
    resolve_target_url,
    is_application_response,
    should_count_as_test,
)
from .response_analyzer import (
    RESPONSE_ANALYZER_VERSION,
    ResponseAnalyzer,
    ResponseFingerprinter,
    PayloadEchoDetector,
    ConfidenceEngine,
    ConfidenceLevel,
    EchoType,
    ResponseDiffType,
    ResponseFingerprint,
    EchoAnalysis,
    ResponseDiff,
    ConfidenceScore,
    AnalysisResult,
    should_report_finding,
)
from .method_discovery import (
    MethodDiscoveryEngine,
    MethodDiscoveryResult,
    DiscoveredEndpoint,
    FormInfo,
    HTTPMethod,
    EndpointSource,
    discover_methods,
)
from .parameter_analyzer import (
    ParameterContextAnalyzer,
    ParameterProfile,
    ContextAnalysisResult,
    ParameterType,
    EntropyLevel,
    ReflectionType,
    AttackRecommendation,
    analyze_parameters,
)
from .negative_control import (
    NegativeControlEngine,
    NegativeControlPayloads,
    NegativeControlBatch,
    ControlTestResult,
    PayloadPair,
    PayloadCategory,
    SignalType,
    SmartPayloadSelector,
    test_negative_control,
    is_signal_or_noise,
)
from .finding_lifecycle import (
    FindingManager,
    Finding,
    FindingState,
    Evidence,
    EvidenceType,
    Severity,
    create_finding_with_evidence,
)
from .oob_engine import (
    OOBEngine,
    OOBToken,
    OOBCallback,
    OOBCallbackStore,
    OOBPayloadGenerator,
    OOBProtocol,
    CallbackType,
    SimpleHTTPCallbackServer,
    ExternalOOBService,
)
from .scope_guard import (
    ScopeGuard,
    ScopeDefinition,
    ScopeViolation,
    ScopeViolationType,
    ScopeMode,
    ScopeGuardMiddleware,
    ScopeViolationError,
    create_scope_from_url,
    is_safe_target,
)

__all__ = [
    "get_logger",
    "setup_logging",
    "RateLimiter",
    "validate_target",
    "validate_url",
    "validate_ip",
    "async_request",
    "resolve_domain",
    "CVSSCalculator",
    # HTTP Transport Engine
    "HTTP_TRANSPORT_VERSION",
    "HTTPTransportEngine",
    "URLCanonicalizer",
    "TransportResult",
    "CanonicalURL",
    "ResponseLayer",
    "RequestStatus",
    "ProtocolPolicy",
    "SmartBackoff",
    "resolve_target_url",
    "is_application_response",
    "should_count_as_test",
    # Response Analyzer (False Positive Prevention)
    "RESPONSE_ANALYZER_VERSION",
    "ResponseAnalyzer",
    "ResponseFingerprinter",
    "PayloadEchoDetector",
    "ConfidenceEngine",
    "ConfidenceLevel",
    "EchoType",
    "ResponseDiffType",
    "ResponseFingerprint",
    "EchoAnalysis",
    "ResponseDiff",
    "ConfidenceScore",
    "AnalysisResult",
    "should_report_finding",
    # Method Discovery Engine (Intelligent Scanning)
    "MethodDiscoveryEngine",
    "MethodDiscoveryResult",
    "DiscoveredEndpoint",
    "FormInfo",
    "HTTPMethod",
    "EndpointSource",
    "discover_methods",
    # Parameter Context Analyzer (Intelligent Payloads)
    "ParameterContextAnalyzer",
    "ParameterProfile",
    "ContextAnalysisResult",
    "ParameterType",
    "EntropyLevel",
    "ReflectionType",
    "AttackRecommendation",
    "analyze_parameters",
    # Negative Control System (Signal vs Noise)
    "NegativeControlEngine",
    "NegativeControlPayloads",
    "NegativeControlBatch",
    "ControlTestResult",
    "PayloadPair",
    "PayloadCategory",
    "SignalType",
    "SmartPayloadSelector",
    "test_negative_control",
    "is_signal_or_noise",
    # Finding Lifecycle Manager (Professional Reports)
    "FindingManager",
    "Finding",
    "FindingState",
    "Evidence",
    "EvidenceType",
    "Severity",
    "create_finding_with_evidence",
    # OOB Engine (Out-of-Band Detection)
    "OOBEngine",
    "OOBToken",
    "OOBCallback",
    "OOBCallbackStore",
    "OOBPayloadGenerator",
    "OOBProtocol",
    "CallbackType",
    "SimpleHTTPCallbackServer",
    "ExternalOOBService",
    # Scope Guard (Legal & Safety)
    "ScopeGuard",
    "ScopeDefinition",
    "ScopeViolation",
    "ScopeViolationType",
    "ScopeMode",
    "ScopeGuardMiddleware",
    "ScopeViolationError",
    "create_scope_from_url",
    "is_safe_target",
]
